site_name: DJKal Library
theme: ivory
nav:
- Home: index.md
- OpenShift:
  - Skills Needed for Install: skills-needed.md
- General:
  - Setup MKDocs: mkdocs-setup.md
- MQ:
  - RDQM HA Install: MQ-RDQM-Install.md
- CP4D:
  - CP4D Upgrade Steps: CP4D_Upgrade.md

  